---
development:
  cloud_name: ha94ojzez
  api_key: ENV['CLOUDINARY_KEY']
  api_secret: ENV['CLOUDINARY_SECRET_KEY']
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: ha94ojzez
  api_key: ENV['CLOUDINARY_KEY']
  api_secret: ENV['CLOUDINARY_SECRET_KEY']
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: ha94ojzez
  api_key: ENV['CLOUDINARY_KEY']
  api_secret: ENV['CLOUDINARY_SECRET_KEY']
  enhance_image_tag: true
  static_file_support: false